package rvm.vector.wall;

import com.google.inject.Inject;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.connection.LoginEvent;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.plugin.annotation.DataDirectory;
import com.velocitypowered.api.proxy.ProxyServer;
import org.slf4j.Logger;

import java.nio.file.Path;
import java.sql.*;
import java.util.UUID;

@Plugin(
    id = "rvmvectorwall",
    name = "RVM VectorWall",
    version = "1.0.0",
    authors = {"RVM Groups (Forgotten Private Coalition)"}
)
public class _rvm00000 {

    private final ProxyServer server;
    private final Logger logger;
    private final Path dataDirectory;
    private Connection connection;

    @Inject
    public _rvm00000(ProxyServer server, Logger logger, @DataDirectory Path dataDirectory) {
        this.server = server;
        this.logger = logger;
        this.dataDirectory = dataDirectory;
    }

    public boolean debugAddToken(String uuidString) {
        String sql = "INSERT INTO tokens (uuid) VALUES (?)";
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, uuidString);
            stmt.executeUpdate();
            logger.info("[DEBUG] Token added for UUID: " + uuidString);
            return true;
        } catch (SQLException e) {
            if (e.getErrorCode() == 23505) {
                logger.warn("[DEBUG] Token already exists for UUID: " + uuidString);
            } else {
                logger.error("[DEBUG] Failed to add token for UUID: " + uuidString, e);
            }
            return false;
        }
    }

    @Subscribe
    public void onProxyInitialize(ProxyInitializeEvent event) {
        try {
            connectToDatabase();
            createTableIfNotExists();
            //debugAddToken("00000000-0000-0000-0000-000000000000");
            logger.info("RVM VectorWall has been enabled successfully!");
        } catch (SQLException e) {
            logger.error("Failed to initialize database connection!", e);
        } catch (ClassNotFoundException e) {
            logger.error("HSQLDB Driver not found!", e);
        }
    }

    private void connectToDatabase() throws SQLException, ClassNotFoundException {
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        
        String url = "jdbc:hsqldb:file:./RVMGroups/vector/vectorwall;hsqldb.lock_file=false;shutdown=true";
        connection = DriverManager.getConnection(url, "sa", "");
    }

    private void createTableIfNotExists() throws SQLException {
        String sql = "CREATE TABLE IF NOT EXISTS tokens (" +
                     "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                     "uuid VARCHAR(36) NOT NULL UNIQUE" +
                     ")";
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(sql);
        }
    }

    @Subscribe
    public void onPlayerLogin(LoginEvent event) {
        UUID playerUUID = event.getPlayer().getUniqueId();
        String uuidString = playerUUID.toString();

        try {
            if (checkAndDeleteToken(uuidString)) {
            } else {
                event.setResult(LoginEvent.ComponentResult.denied(
                    net.kyori.adventure.text.Component.text("You are not authorized to join this server!")
                ));
                logger.info("Knocked " + uuidString);
            }
        } catch (SQLException e) {
            logger.error("Database error while processing player " + uuidString, e);
            event.setResult(LoginEvent.ComponentResult.denied(
                net.kyori.adventure.text.Component.text("Internal server error. Please try again later.")
            ));
        }
    }

    private boolean checkAndDeleteToken(String uuid) throws SQLException {
        String selectSql = "SELECT id FROM tokens WHERE uuid = ?";
        String deleteSql = "DELETE FROM tokens WHERE uuid = ?";
        
        try (PreparedStatement selectStmt = connection.prepareStatement(selectSql)) {
            selectStmt.setString(1, uuid);
            ResultSet rs = selectStmt.executeQuery();
            
            if (rs.next()) {
                int sectionNumber = rs.getInt("id");
                
                try (PreparedStatement deleteStmt = connection.prepareStatement(deleteSql)) {
                    deleteStmt.setString(1, uuid);
                    deleteStmt.executeUpdate();
                }
                
                logger.info("Passed " + uuid + ", section " + sectionNumber);
                return true;
            }
            return false;
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public void closeConnection() {
        if (connection != null) {
            try {
                try (Statement stmt = connection.createStatement()) {
                    stmt.execute("SHUTDOWN");
                }
                connection.close();
            } catch (SQLException e) {
                logger.error("Failed to close database connection!", e);
            }
        }
    }
}